version: 0.2.1

name: first-experiment
description: This is a basic experiment leveraging the newly staff shipped GitHub Stacks feature.

branding:
 icon: 'cloud'
 color: 'blue'

inputs:
  - name: required_approving_review_count
    description: Number of reviewers required to approve pull requests
    required: true
    default: 2
    valid-values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6

  - name: additional_self_hosted_runner_group
    description: Name of additional self-hosted runner group to requested for GitHub Actions workflows
    valid-values:
      - Premium

configs:
  branches:
    - name: main
      parameters:
        allow-deletions: false
        allow-force-pushes: false
        dismiss-stale-reviews: true
        enforce-admins: true
        require-code-owner-reviews: true
        required-approving_review_count: ${{ inputs.required_approving_review_count }}
